# Generated by Django 4.2 on 2023-04-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField()),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('HP', 'hplip'), ('DL', 'delllip'), ('MS', 'mouse'), ('KY', 'keyboard'), ('AD', 'Adapter'), ('PR', 'Processor')], max_length=2)),
                ('product_images', models.ImageField(upload_to='product')),
            ],
        ),
    ]
