# Generated by Django 4.2 on 2023-04-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LP', 'Laptop'), ('CH', 'Charges'), ('CO', 'Computer'), ('PT', 'Printer'), ('SW', 'Switch')], max_length=2),
        ),
    ]
